# font
font_family CodeNewRoman Nerd Font Mono
force_ltr yes
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13
disable_ligatures always

# cursor
cursor #ffffff
cursor_text_color #232323
cursor_shape block

# scrollbar
scrollbar never

# colorscheme
background_opacity 0.85
background #000000
background_image none

# window
enabled_layouts tall

# tabs
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 1.0
tab_bar_style separator
tab_separator "     "
tab_bar_align left

tab_bar_background #000000
active_tab_foreground #ffffff
active_tab_background #000000
active_tab_font_style bold
inactive_tab_foreground #898989
inactive_tab_background #000000
