# font
font_family FiraCode Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 13

# cursor
cursor #ffffff
cursor_text_color #232323
cursor_shape block

# scrollbar
scrollbar never

# colorscheme
background_opacity 0.8
background #000000

color252 #343434
color254 #ababab
color253 #555555
color255 #ffffff
color0 #000000
