# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=Super+Shift,r,reload_config

# exit
bind=Super+Shift,m,quit
bind=Super+Shift,q,killclient,

# switch layout
bind=Super,n,switch_layout

# gaps
# bind=Alt+Shift,X,incgaps,1
# bind=Alt+Shift,Z,incgaps,-1
# bind=Alt+Shift,R,togglegaps

# movewin
# bind=Ctrl+Shift,Up,movewin,+0,-50
# bind=Ctrl+Shift,Down,movewin,+0,+50
# bind=Ctrl+Shift,Left,movewin,-50,+0
# bind=Ctrl+Shift,Right,movewin,+50,+0

# resizewin
# bind=Ctrl+Alt,Up,resizewin,+0,-50
# bind=Ctrl+Alt,Down,resizewin,+0,+50
# bind=Ctrl+Alt,Left,resizewin,-50,+0
# bind=Ctrl+Alt,Right,resizewin,+50,+0
