keymode=default
bind=None,XF86AudioLowerVolume,spawn_shell,pactl set-sink-volume @DEFAULT_SINK@ -5%
bind=None,XF86AudioRaiseVolume,spawn_shell,pactl set-sink-volume @DEFAULT_SINK@ +5%
bind=None,XF86AudioMute,spawn_shell,pactl set-sink-mute @DEFAULT_SINK@ toggle
bind=None,XF86HomePage,spawn,thunar
bind=None,XF86Search,spawn,firefox
bind=None,XF86AudioPrev,spawn_shell,playerctl position 5-
bind=None,XF86AudioNext,spawn_shell,playerctl position 5+
bind=None,XF86AudioPlay,spawn_shell,playerctl play-pause

# screenshot
bind=Super,Print,spawn_shell,grim - | wl-copy
bind=None,Print,spawn_shell,grim -g "$(slurp)" - | wl-copy

# menu and terminal
bind=Super,d,spawn,rofi -show drun
bind=Super,Return,spawn,kitty

