keymode=default
# switch window focus
bind=Super,Tab,focusstack,next
bind=Super,h,focusdir,left
bind=Super,l,focusdir,right
# bind=Super,k,focusdir,up
# bind=Super,j,focusdir,down

# swap window
bind=Super+Shift,h,exchange_client,left
bind=Super+Shift,l,exchange_client,right
# bind=Super+Shift,k,exchange_client,up
# bind=Super+Shift,j,exchange_client,down

# switch window status
bind=Super+Shift,g,toggleglobal,
bind=Alt,Tab,toggleoverview,
bind=Super,backslash,togglefloating,
bind=Super+Shift,a,togglemaximizescreen,
bind=Super+Shift,f,togglefullscreen,
# bind=Super+Shift,f,togglefakefullscreen,
bind=Super,Backspace,minimized,
bind=Super,o,toggleoverlay,
bind=Super+Shift,Backspace,restore_minimized
bind=Alt,z,toggle_scratchpad

# scroller layout
bind=Super,f,set_proportion,1.0
bind=Super,r,switch_proportion_preset,

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=Super,btn_left,moveresize,curmove
mousebind=Super,btn_middle,togglemaximizescreen,0
mousebind=Super,btn_right,moveresize,curresize
