borderpx=3
rootcolor=0xffffffff 
bordercolor=0x000000ff 
focuscolor=0xff6767ff 
maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
