---@diagnostic disable: undefined-global
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output = "eDP-1",
	position = "auto",
	scale = "1",
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "auto",
	scale = "1",
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "kitty"
local fileManager = "thunar"
local menu = "rofi -show drun"
local control_center = "noctalia msg panel-toggle control-center"
local session = "noctalia msg panel-toggle session"
local status_bar = "noctalia"
local wallpaper = "awww-daemon"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
	hl.exec_cmd(status_bar)
	hl.exec_cmd("noctalia msg bar-auto-hide-set true default eDP-1")
	-- hl.exec_cmd(wallpaper)
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 10,

		border_size = 2,

		col = {
			active_border = { colors = { "#aa5555" }, angle = 0 },
			inactive_border = "#aaaa22",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = false,

		layout = "scrolling",
	},

	decoration = {
		rounding = 5,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 1.0,

		shadow = {
			enabled = true,
			range = 4,
			render_power = 3,
			color = 0xee1a1a1a,
		},

		blur = {
			enabled = true,
			size = 10,
			passes = 1,
			vibrancy = 0.1696,
		},
	},

	animations = {
		enabled = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "quick" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "quick", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "linear", style = "slide" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "slidevert" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 5, bezier = "quick", style = "slidevert" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 5, bezier = "quick", style = "slidevert" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
hl.workspace_rule({ workspace = "1", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-1", persistent = true, layout = "master" })
hl.workspace_rule({ workspace = "3", monitor = "HDMI-A-1", persistent = true, layout = "master" })
hl.workspace_rule({ workspace = "4", monitor = "HDMI-A-1", persistent = true, layout = "dwindle" })
hl.workspace_rule({ workspace = "5", monitor = "HDMI-A-1", persistent = true, layout = "dwindle" })
hl.workspace_rule({ workspace = "6", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-1", persistent = true })
hl.workspace_rule({ workspace = "10", monitor = "eDP-1", persistent = true, layout = "master" })
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
		orientation = "left",
		mfact = 0.65,
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
		column_width = 1,
		focus_fit_method = 1,
		explicit_column_widths = "0.25, 0.5, 0.75, 1",
		direction = "right",
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us,ru",
		kb_variant = "",
		kb_model = "",
		kb_options = "grp:win_space_toggle",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local SUPER = "SUPER" -- Sets "Windows" key as main modifier
local SHIFT = "SHIFT" -- Sets "Windows" key as main modifier
local LEFT = "H"
local RIGHT = "L"
local UP = "K"
local DOWN = "J"

local function key_to_str(main, keys)
	if keys ~= nil then
		if type(keys) == "table" then
			return main .. " + " .. table.concat(keys, " + ")
		else
			return main .. " + " .. tostring(keys)
		end
	else
		return table.concat(main, " + ")
	end
end

local function Super(keys)
	return key_to_str(SUPER, keys)
end

local function Alt(keys)
	return key_to_str("ALT", keys)
end

local function Ctrl(keys)
	return key_to_str("CTRL", keys)
end

-- bind=Super,Print,spawn_shell,grim - | wl-copy
-- bind=None,Print,spawn_shell,grim -g "$(slurp)" - | wl-copy

hl.bind(Super("Print"), hl.dsp.exec_cmd("hyprshot -m output --clipboard-only"))
hl.bind(Alt("Print"), hl.dsp.exec_cmd("hyprshot -m window --clipboard-only"))
hl.bind(Ctrl("Print"), hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

hl.bind(Super({ SHIFT, "Print" }), hl.dsp.exec_cmd("hyprshot -m output "))
hl.bind(Alt({ SHIFT, "Print" }), hl.dsp.exec_cmd("hyprshot -m window "))
hl.bind(Ctrl({ SHIFT, "Print" }), hl.dsp.exec_cmd("hyprshot -m region "))

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(Super("Return"), hl.dsp.exec_cmd(terminal))
hl.bind(Super({ SHIFT, "Q" }), hl.dsp.window.close())
hl.bind(Super({ SHIFT, "Escape" }), hl.dsp.exec_cmd(session))

hl.bind(Super("R"), hl.dsp.submap("resize"))

local function resize(direction)
	local ws = hl.get_active_workspace()
	if ws.tiled_layout == "scrolling" and type(direction) == "string" then
		if direction == "up" or direction == "down" then
			return
		end
		local dir = {
			left = "colresize -0.01",
			right = "colresize +0.01",
			full = "colresize 1",
		}
		hl.dispatch(hl.dsp.layout(dir[direction]))
	else
		if direction == "full" then
			return
		end
		local dir = {
			left = {
				x = -10,
				y = 0,
			},
			right = {
				x = 10,
				y = 0,
			},
			up = {
				x = 0,
				y = 10,
			},
			down = {
				x = 0,
				y = -10,
			},
		}
		hl.dispatch(hl.dsp.window.resize({ x = dir[direction].x, y = dir[direction].y, relative = true }))
	end
end

hl.define_submap("resize", function()
	hl.bind(UP, function()
		resize("up")
	end, { repeating = true })
	hl.bind(DOWN, function()
		resize("down")
	end, { repeating = true })
	hl.bind(LEFT, function()
		resize("left")
	end, { repeating = true })
	hl.bind(RIGHT, function()
		resize("right")
	end, { repeating = true })
	hl.bind("F", function()
		resize("full")
	end)

	hl.bind("Escape", hl.dsp.submap("reset"))
end)

hl.bind(Super("F"), hl.dsp.layout("colresize 1"))
hl.bind(Super({ SHIFT, "F" }), hl.dsp.window.fullscreen())

hl.bind(
	Super({ SHIFT, "M" }),
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(Super("E"), hl.dsp.exec_cmd(fileManager))
hl.bind(Super("V"), hl.dsp.window.float({ action = "toggle" }))
hl.bind(Super("D"), hl.dsp.exec_cmd(menu))
hl.bind(Super({ SHIFT, "D" }), hl.dsp.exec_cmd(control_center))
hl.bind(Super("P"), hl.dsp.window.pseudo())
-- hl.bind(Super("J"), hl.dsp.layout("togglesplit")) -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(Super(LEFT), hl.dsp.focus({ direction = "left" }))
hl.bind(Super(RIGHT), hl.dsp.focus({ direction = "right" }))
hl.bind(Super(UP), hl.dsp.focus({ direction = "up" }))
hl.bind(Super(DOWN), hl.dsp.focus({ direction = "down" }))

local function get_dir_window(ws, direction)
	local active_window = hl.get_active_window()
	if not active_window then
		return
	end
	local active_x = active_window.at.x
	local windows = hl.get_workspace_windows(ws)
	if windows and #windows > 1 then
		for _, window in ipairs(windows) do
			local x = window.at.x
			if direction == "right" then
				if x > active_x then
					return window
				end
			end
			if x < active_x then
				return window
			end
		end
	end
end

local function move_win(direction)
	local ws = hl.get_active_workspace()
	if ws.tiled_layout == "scrolling" then
		if get_dir_window(ws, direction) then
			hl.dispatch(hl.dsp.window.swap({ direction = direction }))
			return
		end
	end
	hl.dispatch(hl.dsp.window.move({ direction = direction }))
end

hl.bind(Super({ SHIFT, LEFT }), function()
	move_win("left")
end)

hl.bind(Super({ SHIFT, RIGHT }), function()
	move_win("right")
end)

hl.bind(Super({ SHIFT, UP }), hl.dsp.window.move({ direction = "up" }))
hl.bind(Super({ SHIFT, DOWN }), hl.dsp.window.move({ direction = "down" }))

hl.bind(Super("TAB"), hl.dsp.focus({ workspace = "e+1" }))
hl.bind(Super({ SHIFT, "TAB" }), hl.dsp.focus({ workspace = "e-1" }))

hl.bind(Alt({ SHIFT, "TAB" }), hl.dsp.window.swap({ next = true }))
hl.bind(Alt("TAB"), function()
	local ws = hl.get_active_workspace()
	if ws.tiled_layout == "monocle" then
		hl.dispatch(hl.dsp.layout("cyclenext"))
		return
	end
	hl.dispatch(hl.dsp.window.cycle_next())
end)

-- Switch workspaces with mainMod + [1-9]
-- Move active window to a workspace with mainMod + SHIFT + [1-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(Super(key), hl.dsp.focus({ workspace = i }))
	hl.bind(Super({ SHIFT, key }), hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(Super("S"), hl.dsp.workspace.toggle_special("magic"))
hl.bind(Super({ SHIFT, "S" }), hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(Super("mouse_down"), hl.dsp.focus({ workspace = "e-1" }))
hl.bind(Super("mouse_up"), hl.dsp.focus({ workspace = "e+1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(Super("mouse:272"), hl.dsp.window.drag(), { mouse = true })
hl.bind(Super("mouse:273"), hl.dsp.window.resize(), { mouse = true })

local fn_keys = {
	XF86AudioRaiseVolume = "wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+",
	XF86AudioLowerVolume = "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-",
	XF86AudioMute = "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle",
	XF86AudioMicMute = "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle",
	XF86MonBrightnessUp = "brightnessctl -e4 -n2 set 5%+",
	XF86MonBrightnessDown = "brightnessctl -e4 -n2 set 5%-",
	XF86AudioNext = "playerctl next",
	XF86AudioPause = "playerctl play-pause",
	XF86AudioPlay = "playerctl play-pause",
	XF86AudioPrev = "playerctl previous",
}

for key, action in pairs(fn_keys) do
	hl.bind(key, hl.dsp.exec_cmd(action), { locked = true, repeating = true })
end

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful
hl.window_rule({
	name = "TLauncher",
	match = { class = "org-tlauncher-tlauncher-rmo-TLauncher" },
	float = true,
})

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})
