---@diagnostic disable: undefined-global
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

hl.config({ autogenerated = false }) -- remove this line to remove the warning

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output = "eDP-1",
	position = "auto",
	scale = "1",
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "preferred",
	position = "auto",
	scale = "1",
})

-------------------
---- EVENTS ----
-------------------

require("lua.events")

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

require("lua.env")

-- look and feel (theme, colorscheme, gaps, animations, borders)
require("lua.theme")

-- rules
require("lua.rules")

-- layouts config

require("lua.layouts")

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

require("lua.input")

---------------------
---- KEYBINDINGS ----
---------------------

require("lua.binds")
