# windowrule
windowrule=monitor:HDMI-A-1,isfloating:1,appid:org-tlauncher-tlauncher-rmo-TLauncher
windowrule=monitor:HDMI-A-1,isfloating:1,appid:hyp.exe
windowrule=width:800,height:800,monitor:HDMI-A-1,isfloating:1,title:parametrs

