# rules of mangoWM
source=./rules/monitor.conf
source=./rules/window.conf
source=./rules/tag.conf
source=./rules/layer.conf

# autostarts
source=./exec.conf

# input settings
source=./input/keyboard.conf
source=./input/trackpad.conf

# keymaps
source=./bind/tags.conf
source=./bind/core.conf
source=./bind/windows.conf
source=./bind/user.conf
source=./bind/monitor.conf

# visual settings
source=./appearance/animations.conf
source=./appearance/effects.conf
source=./appearance/borders.conf
source=./appearance/gaps.conf

# layouts settings
source=./layouts/scroller.conf
source=./layouts/master.conf
source=./layouts/overview.conf
source=./layouts/misc.conf
