# Autostarts
exec=awww-daemon
exec=~/config/lua_scripts/handlers/client.sh
exec=~/config/lua_scripts/handlers/kb.sh
exec=~/config/lua_scripts/handlers/tag.sh
exec=~/config/lua_scripts/handlers/keymode.sh
exec-once=qs
exec-once=/usr/lib/xdg-desktop-portal

