# Autostarts
exec=awww-daemon
exec=~/config/lua_scripts/handlers/client.sh
exec=~/config/lua_scripts/handlers/kb.sh
exec=~/config/lua_scripts/handlers/tag.sh
exec=~/config/lua_scripts/handlers/keymode.sh
exec-once=nwg-wrapper -s date-time.sh -o eDP-1 -r 1000 -p left -a start -mt 100 -ml 100
exec-once=qs
exec-once=/usr/lib/xdg-desktop-portal

