# Autostarts
exec=awww-daemon
exec=~/Programming/Lua/mmsg/tag_script.sh
exec=~/Programming/Lua/mmsg/kb_script.sh
exec-once=nwg-wrapper -s date-time.sh -o eDP-1 -r 1000 -p left -a start -mt 100 -ml 100
exec-once=qs
exec-once=/usr/lib/xdg-desktop-portal

